[workspace.package]
version = "0.5.54"
authors = ["John Schiefelbein"]
license = "MIT"
edition = "2024"

[workspace.dependencies]
bevy_ecs = { version = "0.19", default-features = false, features = [
    "debug",
    "std",
] }
egor = { version = "0.10.0", default-features = false, features = [
    "webgl",
    "ui",
] }
noise = "0.9.0"
starbloom-derive = { version = "^0", path = "crates/starbloom-derive" }
starbloom-intro = { version = "^0", path = "crates/starbloom-intro" }
starbloom-map = { version = "^0", path = "crates/starbloom-map" }
starbloom-worldgen = { version = "^0", path = "crates/starbloom-worldgen" }
starbloom-camera = { version = "^0", path = "crates/starbloom-camera" }
starbloom-tiles = { version = "^0", path = "crates/starbloom-tiles" }
starbloom-base = { version = "^0", path = "crates/starbloom-base" }
starbloom-input = { version = "^0", path = "crates/starbloom-input" }
starbloom-states = { version = "^0", path = "crates/starbloom-states" }
rand = { version = "0.10.3", default-features = false, features = [
    "std",
    "std_rng",
] }
starbloom-bootstrap = { version = "^0", path = "crates/starbloom-bootstrap" }
log = "0.4.33"
egor_glue = "0.10.0"
web-sys = { version = "0.3.106", features = [
    "Window",
    "Navigator",
    "Document",
] }
naia-server = "0.25.0"
naia-client = "0.25.0"
naia-shared = "0.25.0"

[workspace]
resolver = "3"
members = [
    "crates/starbloom-base",
    "crates/starbloom-camera",
    "crates/starbloom-derive",
    "crates/starbloom-input",
    "crates/starbloom-intro",
    "crates/starbloom-map",
    "crates/starbloom-tiles",
    "crates/starbloom-worldgen",
    "crates/starbloom-states",
    "crates/starbloom-bootstrap",
]

[package]
name = "starbloom"
description = "A game"
version.workspace = true
license.workspace = true
edition.workspace = true
homepage = "https://sb.readthedocs.io"
repository = "https://github.com/1kgd/sb"
publish = true

[dependencies]

egor.workspace = true
bevy_ecs.workspace = true
egor_glue.workspace = true
web-sys = { workspace = true, optional = true }
starbloom-base.workspace = true
starbloom-camera.workspace = true
starbloom-intro = { workspace = true, optional = true }
starbloom-map.workspace = true
starbloom-tiles.workspace = true
starbloom-worldgen.workspace = true
starbloom-input.workspace = true
starbloom-states.workspace = true
starbloom-bootstrap.workspace = true
starbloom-derive.workspace = true
wasm-logger = { version = "0.2.0", optional = true }
cosmic-text = { version = "0.19.0", optional = true }
env_logger = { version = "0.11.11", optional = true }
console_error_panic_hook = { version = "0.1.7", optional = true }
rand.workspace = true
naia-client = { workspace = true, optional = true }
naia-server = { workspace = true, optional = true }
naia-shared = { workspace = true, optional = true }

[features]
intro = ["starbloom-bootstrap/intro", "dep:starbloom-intro"]
debug_ui = []
debug_logging = []
env_logger = ["dep:env_logger"]
mobile = ["starbloom-input/mobile"]
web = [
    "mobile",
    "starbloom-input/gilrs",
    "cosmic-text?/wasm-web",
    "starbloom-base/web",
    "dep:web-sys",
    "dep:wasm-logger",
    "dep:console_error_panic_hook",
    "naia-shared?/wbindgen",
    "naia-client?/wbindgen",
]
multiplayer = ["dep:naia-shared"]

server = ["multiplayer", "dep:naia-server", "starbloom-derive/server"]
client = ["multiplayer", "dep:naia-client", "starbloom-derive/client"]

mobile_build = ["intro", "mobile", "env_logger"]
desktop_build = [
    "intro",
    "starbloom-input/gilrs",
    "env_logger",
    "client",
    "server",
]
web_build = ["intro", "web"]
server_build = ["env_logger", "server"]

dev = ["debug_ui", "debug_logging"]
cosmic-text = ["dep:cosmic-text"]

default = ["desktop_build"]

[lib]
name = "sb"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "starbloom"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
