[package]
name = "starbloom-derive"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "A sub package for starbloom"

[dependencies]
quote = "1.0.47"
syn = { version = "3.0.6", features = ["full", "parsing"] }

[lib]
proc-macro = true

[features]
multiplayer = []
client = ["multiplayer"]
server = ["multiplayer"]