[package]
name = "starbloom-bootstrap"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "A sub package for starbloom"

[dependencies]
starbloom-base.workspace = true
starbloom-states.workspace = true
bevy_ecs.workspace = true

[features]
intro = []
