[package]
name = "starbloom-input"
description = "sub-package for starbloom"
license.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
starbloom-base.workspace = true
egor.workspace = true
bevy_ecs.workspace = true
gilrs = "0.11.2"

[features]
mobile = []
gilrs = []
