name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cargo Bump
      uses: tj-actions/cargo-bump@v3.0.2
    - name: Publish to crates.io
      run: cargo publish --workspace
