name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cargo Bump
      uses: dimitrmo/cargo-verison-action@1.0.0
    - name: Authenticate to crates.io
      uses: rust-lang/crates-io-auth-action@v1.0.5
    - name: Publish to crates.io
      run: cargo publish --workspace
